services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_bd_produtosapi
    restart: always
    environment:
      POSTGRES_DB: bd_produtosapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: local/br-com-coti/produtos-api:1.0.0  # Use the Jib-built image
    container_name: produtosapi_app
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: senha123
    restart: always

volumes:
  postgres_data:
