name: SonarQube Scan

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ github.run_id }}
          restore-keys: sonar-${{ runner.os }}-

      - name: Run SonarQube Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.host.url=http://your-sonarqube-server-url \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
